print ("Willdel Bravo")
print ("Barangay Uno Buenavista, Marinduque")
print ("Febraury 06, 2004")
print ("College of Information and Computing Sciences")
print ("Bachelor of Science in Information Technology")
print ("2nd year - B")
print ("Photography")
print ("Watching anime")
print ("Learning about history")
print ("Gaming")
print ("Reading manga")
